### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by Mithgol** [ovidiuch/obvious-buttons#4]
Please visit http://choosealicense.com/ and pick some OSS license that would allow people to use your buttons.

**Comment by ovidiuch** [comment]
There was already a license mentioned in the source files: https://github.com/skidding/obvious-buttons/blob/master/src/obvious-buttons.less#L6

But I added a LICENSE file as well, since that was probably hard to spot: https://github.com/skidding/obvious-buttons/blob/master/LICENSE

Thanks

**Comment by Mithgol** [comment]
Thanks.
